server {
    # Non-root user chỉ được dùng port >= 1024 (chuẩn nhất là 8080)
    listen 8080;
    server_name localhost;

    # 1. Phục vụ giao diện Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html chat.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Reverse Proxy: Điều hướng API gọi xuống Backend
    location /backend-api/ {
        proxy_pass http://backend:8000/backend-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}